### ISSUE TITLE
System subtracts by 1 the Absence Date

### ISSUE THREAD

**Issue by mapacheco-mml** [timeoff-management/application#150] opened 2017-05-15 16:23 UTC
Hello!

My name is Marcelo, I am from Brazil.

I have installed the last version (master) of the app on a Windows Server. But, when saving an absence, the system subtracts by 1 the date I have inputted (selected on the calendar component, in fact). So, for example, I placed 18th, May... and when checking my the calendar on Team View or even the Calendar page, the displayed date is 17th, May.

I checked the information inside the database and the date is being saved correctly, so I thought maybe that should be something related to a kind of timezone issue for node/jscript and after searching on GitHub seems this issue was found in the past (https://github.com/timeoff-management/application/issues/107).

I thought it was fixed, but the last version available (master) seems to have it with problems yet, once the version I have tried on the Internet works fine.

Please, could you check it and let me know if this was really fixed or it still on the way? Or if is there any kind of setting that I should do in order to make it run?

Thanks
Marcelo

**Comment by vpp** [comment] 2017-05-15 17:22
Hi Marcelo,

Yeah, the problem is indeed because of time zones feature is missing in the application.

There is a ticket #58 to address that. It has quite high priority, and involves some work.. please keep an eye on it for updates.

There is "workaround" (it worked for some people): set time on the server where you run the app to be UTC. That might work be ok for you if your location is not far from Europe time zones; although if you are closer to Pacific that will not...

The issue with time zones is really annoying as it upset lots of potential users from USA.

Thanks
Pavlo

**Comment by mapacheco-mml** [comment] 2017-05-15 17:34
Hi Pavlo!

First of all, thank you so much for the quick feedback. Yeah, issues with time zones are always annoying and they take time to be solved.

Regarding the workaround, actually I did it before you answering this thread and it worked for us. I am gonna check if how we are supposed to handle such configuration in our server.

Have a good week!
Marcelo

**Comment by vpp** [comment] 2017-05-15 19:03
Thank you Marcelo

I am closing this ticket as #58 will take care of the issue

**Closed** 2017-05-15 19:03 UTC
